name: fenics-env-clean
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cctools_osx-arm64=1010.6=h3b4f5d3_6
  - clang=18.1.8=default_h675cc0c_3
  - clang-18=18.1.8=default_h5c12605_3
  - clang_impl_osx-arm64=18.1.8=h2ae9ea5_24
  - clang_osx-arm64=18.1.8=h07b0088_24
  - clangxx=18.1.8=default_h675cc0c_3
  - clangxx_impl_osx-arm64=18.1.8=h555f467_24
  - clangxx_osx-arm64=18.1.8=h07b0088_24
  - compiler-rt=18.1.8=h856b3c1_1
  - compiler-rt_osx-arm64=18.1.8=h832e737_1
  - eigen=3.4.0=h1995070_0
  - fenics-dijitso=2019.1.0=pyhd8ed1ab_39
  - fenics-dolfin=2019.1.0=py310h57e9257_58
  - fenics-ffc=2019.1.0=pyhd8ed1ab_40
  - fenics-fiat=2019.1.0=pyhd8ed1ab_40
  - fenics-libdolfin=2019.1.0=h827c010_58
  - fenics-ufl=2019.1.0=pyhd8ed1ab_16
  - fftw=3.3.10=mpi_mpich_hd148bab_10
  - gmp=6.3.0=h7bae524_2
  - hdf5=1.14.6=mpi_mpich_h13a04de_1
  - hypre=2.32.0=mpi_mpich_h189fe77_1
  - icu=75.1=hfee45f7_0
  - krb5=1.21.3=h237132a_0
  - ld64_osx-arm64=951.9=hb6b49e2_6
  - libaec=1.1.3=hebf3989_0
  - libamd=3.3.3=h5087772_7100102
  - libblas=3.9.0=31_h10e41b3_openblas
  - libboost=1.86.0=hc9fb7c5_3
  - libboost-headers=1.88.0=hce30654_0
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libclang-cpp18.1=18.1.8=default_h5c12605_3
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcurl=8.13.0=h73640d1_0
  - libcxsparse=4.4.1=h9e79f82_7100102
  - libcxx=20.1.4=ha82da77_1
  - libcxx-devel=20.1.4=h6dc3340_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.0=h286801f_0
  - libfabric=2.1.0=hce30654_1
  - libfabric1=2.1.0=h5505292_1
  - libffi=3.4.6=h1da3d7d_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.1=hbec27ea_1
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=hfe07756_1
  - libintl=0.24.1=h493aca8_0
  - libklu=2.3.5=h4370aa4_7100102
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libldl=3.3.2=h99b4a89_7100102
  - libllvm18=18.1.8=hc4b4ae8_3
  - liblzma=5.8.1=h39f12f2_1
  - liblzma-devel=5.8.1=h39f12f2_1
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libparu=1.0.0=h317a14d_7100102
  - libptscotch=7.0.6=hcfc2647_1
  - librbio=4.3.4=h99b4a89_7100102
  - libscotch=7.0.6=hd10c9a7_1
  - libspex=3.2.3=h15d103f_7100102
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.49.2=h3f77e49_0
  - libssh2=1.11.1=h1590b86_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libumfpack=6.3.5=h7c2c975_7100102
  - libxml2=2.13.8=h52572c6_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.4=hdb05f8b_0
  - llvm-tools=18.1.8=hc4b4ae8_3
  - llvm-tools-18=18.1.8=hc4b4ae8_3
  - metis=5.1.0=h15f6cfe_1007
  - mpfr=4.2.1=hb693164_3
  - mpi=1.0.1=mpich
  - mpi4py=4.0.3=py310h311049b_101
  - mpich=4.3.0=h9d9a6ae_100
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mumps-include=5.7.3=h71ed9e6_10
  - mumps-mpi=5.7.3=h4795f8b_10
  - ncurses=6.5=h5e97a16_3
  - numpy=2.2.5=py310h4d83441_0
  - openssl=3.5.0=h81ee809_1
  - pandas-stubs=2.2.3.250527=pyhd8ed1ab_1
  - parmetis=4.0.3=ha4b917a_1007
  - pcre2=10.45=ha881caa_0
  - petsc=3.23.2=real_h2e1b521_0
  - petsc4py=3.23.2=np20py310hdef029b_0
  - pip=25.1.1=pyh8b19718_0
  - pkg-config=0.29.2=hde07d2e_1009
  - pkgconfig=1.5.5=pyhd8ed1ab_5
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - python=3.10.17=h6cefb37_0_cpython
  - python_abi=3.10=7_cp310
  - readline=8.2=h1d1bf99_2
  - scalapack=2.2.0=h71a4f75_4
  - setuptools=80.1.0=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.17.0=pyhd8ed1ab_0
  - slepc=3.23.1=real_hf91219e_0
  - slepc4py=3.23.1=np20py310h9341a07_0
  - suitesparse=7.10.1=h3071b36_7100102
  - superlu=7.0.1=h81aaeaf_0
  - superlu_dist=9.1.0=h89afcdd_0
  - sympy=1.14.0=pyh04b8f61_5
  - tapi=1300.6.5=h03f4b80_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h9a6d368_1
  - xz-gpl-tools=5.8.1=h9a6d368_1
  - xz-tools=5.8.1=h39f12f2_1
  - yaml=0.2.5=h3422bc3_2
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.0
      - idna==3.10
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pooch==1.8.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvista==0.45.2
      - requests==2.32.3
      - scipy==1.15.3
      - scooby==0.10.1
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - vtk==9.4.2
prefix: /Users/ih09odap/miniconda3/envs/fenics-env-clean
